"""vNext PR 14 gate tests — Gemini CLI adapter."""

from __future__ import annotations

from pathlib import Path

from zeref.adapters.harnesses.gemini_cli import GeminiCLIAdapter


def test_gemini_context_only_without_signals(monkeypatch) -> None:
    monkeypatch.delenv("GEMINI_CLI_VERSION", raising=False)
    monkeypatch.delenv("GEMINI_VERSION", raising=False)
    monkeypatch.setattr("zeref.adapters.harnesses.gemini_cli.which",
                         lambda cmd: None)
    r = GeminiCLIAdapter().detect()
    assert not r.detected
    assert r.enforcement_level.value == "C"


def test_gemini_embedded_when_env_var(monkeypatch) -> None:
    monkeypatch.setenv("GEMINI_CLI_VERSION", "0.9")
    monkeypatch.setattr("zeref.adapters.harnesses.gemini_cli.which",
                         lambda cmd: None)
    r = GeminiCLIAdapter().detect()
    assert r.detected
    assert r.enforcement_level.value == "A"


def test_gemini_writes_GEMINI_md(tmp_path: Path) -> None:
    written = GeminiCLIAdapter().export_context(
        tmp_path, objective="ship it", permissions={"net": "denied"},
    )
    assert written == [tmp_path / "GEMINI.md"]
    text = written[0].read_text(encoding="utf-8")
    assert text.startswith("<!-- GENERATED BY ZEREF.")
    assert "ship it" in text


def test_gemini_features() -> None:
    r = GeminiCLIAdapter().detect()
    for f in ("GEMINI.md", "extensions", "tools", "MCP"):
        assert f in r.supported_features
