"""vNext PR 12 gate tests — Codex harness adapter."""

from __future__ import annotations

from pathlib import Path

import pytest

from zeref.adapters.harnesses.codex import CodexAdapter


def test_codex_reports_context_only_when_no_binary(tmp_path: Path,
                                                    monkeypatch) -> None:
    monkeypatch.delenv("CODEX_CLI_VERSION", raising=False)
    monkeypatch.setattr("zeref.adapters.harnesses.codex.which", lambda cmd: None)
    report = CodexAdapter().detect()
    assert not report.detected
    assert report.enforcement_level.value == "C"
    assert "codex" in (report.failure_reason or "").lower()


def test_codex_reports_embedded_when_env_var_set(monkeypatch) -> None:
    monkeypatch.setenv("CODEX_CLI_VERSION", "0.4.2")
    monkeypatch.setattr("zeref.adapters.harnesses.codex.which", lambda cmd: None)
    report = CodexAdapter().detect()
    assert report.detected
    assert report.enforcement_level.value == "A"
    assert report.detected_version == "0.4.2"


def test_codex_exports_AGENTS_md(tmp_path: Path) -> None:
    written = CodexAdapter().export_context(
        tmp_path, objective="Ship the feature.",
        permissions={"network": "denied", "fs.write": ["project"]},
    )
    assert written == [tmp_path / "AGENTS.md"]
    text = written[0].read_text(encoding="utf-8")
    assert text.startswith("<!-- GENERATED BY ZEREF.")
    assert "Ship the feature." in text
    assert '"network": "denied"' in text


def test_codex_declares_supported_features() -> None:
    report = CodexAdapter().detect()
    assert "AGENTS.md" in report.supported_features
