"""vNext PR 15 gate tests — Kimi Code harness adapter."""

from __future__ import annotations

from pathlib import Path

from zeref.adapters.harnesses.kimi_code import KimiCodeAdapter


def test_kimi_context_only_without_signals(monkeypatch) -> None:
    monkeypatch.delenv("KIMI_CODE_VERSION", raising=False)
    monkeypatch.delenv("KIMI_CLI_VERSION", raising=False)
    monkeypatch.setattr("zeref.adapters.harnesses.kimi_code.which",
                         lambda cmd: None)
    r = KimiCodeAdapter().detect()
    assert not r.detected
    assert r.enforcement_level.value == "C"


def test_kimi_embedded_when_env_var(monkeypatch) -> None:
    monkeypatch.setenv("KIMI_CODE_VERSION", "1.0")
    monkeypatch.setattr("zeref.adapters.harnesses.kimi_code.which",
                         lambda cmd: None)
    r = KimiCodeAdapter().detect()
    assert r.detected
    assert r.enforcement_level.value == "A"


def test_kimi_writes_KIMI_md(tmp_path: Path) -> None:
    written = KimiCodeAdapter().export_context(
        tmp_path, objective="ship it", permissions={"net": "denied"},
    )
    assert written == [tmp_path / "KIMI.md"]
    assert (tmp_path / "KIMI.md").read_text("utf-8").startswith(
        "<!-- GENERATED BY ZEREF."
    )


def test_kimi_features() -> None:
    r = KimiCodeAdapter().detect()
    for f in ("KIMI.md", "lifecycle_hooks", "plugins", "MCP", "subagents",
              "ACP"):
        assert f in r.supported_features
