"""Doctor checks for local Zeref health."""

from __future__ import annotations

import json
import platform
from dataclasses import asdict, dataclass
from pathlib import Path

from zeref.memory import MEMORY_DIRS, MEMORY_FILES


@dataclass(frozen=True)
class DoctorCheck:
    name: str
    status: str
    detail: str

    def to_dict(self) -> dict:
        return asdict(self)


def run_doctor(root: Path) -> list[DoctorCheck]:
    checks = [
        _python_check(),
        _package_check(),
        _path_check("config", root / "config"),
        _path_check("privacy_files", root / "PRIVACY.md", root / "REDACT.md", root / "SHARING_POLICY.md"),
        _memory_dirs(root),
        _memory_files(root),
        _runtime_path_check("schema", root, root / "memory" / "state" / "schema.json"),
        _runtime_path_check(
            "audit_logs",
            root,
            root / "memory" / "audit" / "writes.jsonl",
            root / "memory" / "audit" / "guard_failures.jsonl",
        ),
        _path_check("permissions", root / "config" / "PERMISSIONS.md"),
    ]
    return checks


def format_doctor(checks: list[DoctorCheck], *, format: str = "text") -> str:
    if format == "json":
        return json.dumps([check.to_dict() for check in checks], indent=2, sort_keys=True) + "\n"
    return "\n".join(f"{check.status.upper()} {check.name}: {check.detail}" for check in checks) + "\n"


def doctor_passed(checks: list[DoctorCheck]) -> bool:
    return all(check.status == "pass" for check in checks)


def _python_check() -> DoctorCheck:
    version = platform.python_version_tuple()
    ok = int(version[0]) == 3 and int(version[1]) >= 11
    return DoctorCheck("python", "pass" if ok else "fail", platform.python_version())


def _package_check() -> DoctorCheck:
    try:
        import zeref  # noqa: F401
    except Exception as exc:
        return DoctorCheck("package", "fail", str(exc))
    return DoctorCheck("package", "pass", "zeref imports")


def _path_check(name: str, *paths: Path) -> DoctorCheck:
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        return DoctorCheck(name, "fail", "missing " + ", ".join(missing))
    return DoctorCheck(name, "pass", "present")


def _runtime_path_check(name: str, root: Path, *paths: Path) -> DoctorCheck:
    missing = [str(path) for path in paths if not path.exists()]
    if missing and _tracked_memory_scaffold_present(root):
        return DoctorCheck(name, "pass", "tracked scaffold present; generated by zeref init")
    if missing:
        return DoctorCheck(name, "fail", "missing " + ", ".join(missing))
    return DoctorCheck(name, "pass", "present")


def _memory_dirs(root: Path) -> DoctorCheck:
    missing = [rel for rel in MEMORY_DIRS if not (root / rel).exists()]
    if missing:
        if _tracked_memory_scaffold_present(root):
            return DoctorCheck("memory_dirs", "pass", "tracked scaffold present; generated by zeref init")
        return DoctorCheck("memory_dirs", "fail", "missing " + ", ".join(missing[:5]))
    return DoctorCheck("memory_dirs", "pass", "present")


def _memory_files(root: Path) -> DoctorCheck:
    missing = [rel for rel in MEMORY_FILES if not (root / rel).exists()]
    if missing:
        if _tracked_memory_scaffold_present(root):
            return DoctorCheck("memory_files", "pass", "tracked scaffold present; generated by zeref init")
        return DoctorCheck("memory_files", "fail", "missing " + ", ".join(missing[:5]))
    return DoctorCheck("memory_files", "pass", "present")


def _tracked_memory_scaffold_present(root: Path) -> bool:
    return (root / "memory" / ".gitkeep").exists() and (root / "memory" / "README.md").exists()
