"""Codex CLI harness adapter (vNext §12.2 ChatGPT Codex)."""

from __future__ import annotations

from pathlib import Path

from zeref.adapters.harnesses.base import (
    HarnessEnforcementLevel,
    HarnessReport,
    env_hint,
    which,
)


AGENTS_MD_BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)


class CodexAdapter:
    name = "codex"

    def detect(self) -> HarnessReport:
        version = env_hint("CODEX_CLI_VERSION")
        # Detection strategy: CODEX_CLI env var OR a `codex` binary on PATH.
        binary = which("codex")
        detected = bool(version) or bool(binary)
        return HarnessReport(
            name=self.name,
            detected=detected,
            detected_version=version or ("cli-on-path" if binary else None),
            enforcement_level=(HarnessEnforcementLevel.embedded if detected
                               else HarnessEnforcementLevel.context_only),
            supported_features=("AGENTS.md", "tools", "plugin_config",
                                 "structured_output"),
            instruction_files=("AGENTS.md",),
            failure_reason=None if detected else "no codex binary or env var",
        )

    def health(self) -> HarnessReport:
        return self.detect()

    def export_context(self, root: Path, *, objective: str,
                        permissions: dict) -> list[Path]:
        target = root / "AGENTS.md"
        text = AGENTS_MD_BANNER + (
            f"# Objective\n\n{objective}\n\n"
            f"# Permission Contract\n\n"
            "```json\n"
            f"{_pretty(permissions)}\n"
            "```\n"
        )
        target.write_text(text, encoding="utf-8")
        return [target]


def _pretty(obj) -> str:
    import json
    return json.dumps(obj, indent=2, sort_keys=True)
