"""Gemini CLI harness adapter (vNext §12.2 Gemini)."""

from __future__ import annotations

import json
from pathlib import Path

from zeref.adapters.harnesses.base import (
    HarnessEnforcementLevel,
    HarnessReport,
    env_hint,
    which,
)

BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)


class GeminiCLIAdapter:
    name = "gemini-cli"

    def detect(self) -> HarnessReport:
        version = env_hint("GEMINI_CLI_VERSION", "GEMINI_VERSION")
        binary = which("gemini")
        detected = bool(version) or bool(binary)
        return HarnessReport(
            name=self.name,
            detected=detected,
            detected_version=version or ("cli-on-path" if binary else None),
            enforcement_level=(HarnessEnforcementLevel.embedded if detected
                               else HarnessEnforcementLevel.context_only),
            supported_features=("GEMINI.md", "extensions", "tools",
                                 "MCP"),
            instruction_files=("GEMINI.md",),
            failure_reason=None if detected else "no gemini binary or env var",
        )

    def health(self) -> HarnessReport:
        return self.detect()

    def export_context(self, root: Path, *, objective: str,
                        permissions: dict) -> list[Path]:
        target = root / "GEMINI.md"
        target.write_text(
            BANNER
            + f"# Objective\n\n{objective}\n\n"
            + "# Permission Contract\n\n```json\n"
            + json.dumps(permissions, indent=2, sort_keys=True)
            + "\n```\n",
            encoding="utf-8",
        )
        return [target]
