"""Hermes adapter (vNext §12.2 Hermes).

Strict ownership boundary:
- Hermes owns: conversation runtime, channels, tool execution, remote
  execution backends.
- Zeref owns: canonical memory, capability trust, team compilation,
  evidence policy, permission policy, cross-harness continuity.

Hermes skill evolution creates PROPOSALS (never silent activations).
Hermes memory is a read-through cache OR disabled — never a
double-writer.
"""

from __future__ import annotations

import json
from pathlib import Path

from zeref.adapters.harnesses.base import (
    HarnessEnforcementLevel,
    HarnessReport,
    env_hint,
    which,
)

BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)


class HermesAdapter:
    name = "hermes"

    def detect(self) -> HarnessReport:
        version = env_hint("HERMES_VERSION")
        binary = which("hermes")
        detected = bool(version) or bool(binary)
        return HarnessReport(
            name=self.name,
            detected=detected,
            detected_version=version or ("cli-on-path" if binary else None),
            enforcement_level=(HarnessEnforcementLevel.sidecar if detected
                               else HarnessEnforcementLevel.context_only),
            supported_features=("HERMES.md", "skill_proposals",
                                 "tool_bridge", "read_through_memory"),
            instruction_files=("HERMES.md",),
            failure_reason=None if detected else "no hermes binary or env var",
        )

    def health(self) -> HarnessReport:
        return self.detect()

    def export_context(self, root: Path, *, objective: str,
                        permissions: dict) -> list[Path]:
        target = root / "HERMES.md"
        text = (
            BANNER
            + f"# Objective\n\n{objective}\n\n"
            + "# Ownership\n\n"
            + "- Hermes owns: conversation runtime, channels, tool "
              "execution, remote execution backends.\n"
            + "- Zeref owns: canonical memory, capability trust, team "
              "compilation, evidence, permission policy.\n\n"
            + "# Permission Contract\n\n```json\n"
            + json.dumps(permissions, indent=2, sort_keys=True)
            + "\n```\n"
            + "\n# Memory Policy\n\n"
            + "Hermes memory operates as a read-through cache. All writes "
              "flow through Zeref's write gate. Direct writes to Hermes "
              "memory are NOT permitted.\n"
        )
        target.write_text(text, encoding="utf-8")
        return [target]
