"""Odysseus adapter (vNext §12.2 Odysseus).

Odysseus owns: UI, workspace features, tool hosting, chat + document
surfaces.
Zeref owns: canonical memory, capability governance, team compilation,
evidence, permissions.

Integration is through authenticated APIs / plugins / MCP where policy
enforcement remains visible.  Do NOT merge AGPL code into Zeref's MIT
core without deliberate licensing review.
"""

from __future__ import annotations

import json
from pathlib import Path

from zeref.adapters.harnesses.base import (
    HarnessEnforcementLevel,
    HarnessReport,
    env_hint,
    which,
)

BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)


class OdysseusAdapter:
    name = "odysseus"

    def detect(self) -> HarnessReport:
        version = env_hint("ODYSSEUS_VERSION")
        endpoint = env_hint("ODYSSEUS_API_ENDPOINT")
        binary = which("odysseus")
        detected = bool(version) or bool(binary) or bool(endpoint)
        return HarnessReport(
            name=self.name,
            detected=detected,
            detected_version=version or (
                "api-endpoint" if endpoint else
                "cli-on-path" if binary else None
            ),
            enforcement_level=(HarnessEnforcementLevel.sidecar if detected
                               else HarnessEnforcementLevel.context_only),
            supported_features=("ODYSSEUS.md", "api_bridge", "plugin_bridge",
                                 "MCP"),
            instruction_files=("ODYSSEUS.md",),
            failure_reason=None if detected else (
                "no odysseus binary, env var, or API endpoint"
            ),
        )

    def health(self) -> HarnessReport:
        return self.detect()

    def export_context(self, root: Path, *, objective: str,
                        permissions: dict) -> list[Path]:
        target = root / "ODYSSEUS.md"
        target.write_text(
            BANNER
            + f"# Objective\n\n{objective}\n\n"
            + "# Integration\n\n"
            + "Zeref integrates with Odysseus via authenticated API / "
              "plugin / MCP. No direct database access; no AGPL code "
              "merged into Zeref's MIT core without licensing review.\n\n"
            + "# Permission Contract\n\n```json\n"
            + json.dumps(permissions, indent=2, sort_keys=True)
            + "\n```\n",
            encoding="utf-8",
        )
        return [target]
