"""xAI / Grok context adapter (vNext §12.2 Grok).

Grok is treated primarily as a provider/API and context-only chat until
a stable first-party extensible harness is verified. Do NOT claim full
harness support without executable integration tests.
"""

from __future__ import annotations

import json
from pathlib import Path

from zeref.adapters.harnesses.base import (
    HarnessEnforcementLevel,
    HarnessReport,
    env_hint,
)

BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)


class GrokContextAdapter:
    name = "grok"

    def detect(self) -> HarnessReport:
        api_key = env_hint("XAI_API_KEY", "GROK_API_KEY")
        detected = bool(api_key)
        return HarnessReport(
            name=self.name,
            detected=detected,
            detected_version="provider-api" if detected else None,
            # Provider only — no runtime enforcement over Grok's chat surface.
            enforcement_level=HarnessEnforcementLevel.context_only,
            supported_features=("GROK.md", "provider_api",
                                 "context_projection"),
            instruction_files=("GROK.md",),
            failure_reason=None if detected else (
                "no XAI_API_KEY / GROK_API_KEY in environment"
            ),
        )

    def health(self) -> HarnessReport:
        return self.detect()

    def export_context(self, root: Path, *, objective: str,
                        permissions: dict) -> list[Path]:
        target = root / "GROK.md"
        target.write_text(
            BANNER
            + f"# Objective\n\n{objective}\n\n"
            + "# Enforcement\n\n"
            + "Grok is a PROVIDER, not a Zeref-governed harness. This "
              "file assembles context for you to paste into a Grok "
              "session; no runtime enforcement is claimed.\n\n"
            + "# Permission Contract\n\n```json\n"
            + json.dumps(permissions, indent=2, sort_keys=True)
            + "\n```\n",
            encoding="utf-8",
        )
        return [target]
