#!/usr/bin/env python3
"""
skill_updater.py — Zeref Self-Improvement Skill Updater
Version: 3.0.0

CRITICAL SAFETY CONSTRAINT: This script ONLY applies changes where "approved": true.
The approval gate cannot be removed. This is an architectural safety requirement
(ICLR 2026, Samsung START 2026, Anthropic Constitutional AI principles).

Usage: python3 scripts/skill_updater.py --report zeref-upgrade-report.md
"""

import json
import sys
import argparse
from pathlib import Path
from datetime import datetime

FLEET_ROOT = Path(__file__).parent.parent
SKILLS_DIR = FLEET_ROOT / "skills"
CHANGELOG_PATH = FLEET_ROOT / "CHANGELOG.md"

def load_report(report_path):
    """Load upgrade proposals from JSON report."""
    path = Path(report_path)
    if not path.exists():
        print(f"❌ Report not found: {report_path}")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)

def apply_upgrade(proposal):
    """Apply a single approved upgrade to a skill file."""
    skill_name = proposal.get("skill")
    injection = proposal.get("injection")
    insert_after = proposal.get("insert_after")

    skill_path = SKILLS_DIR / skill_name / "SKILL.md"
    if not skill_path.exists():
        return f"  ❌ SKIP — skill file not found: {skill_name}"

    content = skill_path.read_text(encoding="utf-8")

    if insert_after and insert_after in content:
        new_content = content.replace(insert_after, insert_after + "\n\n" + injection)
        skill_path.write_text(new_content, encoding="utf-8")
        return f"  ✅ Applied: {skill_name} — {proposal.get('description', 'upgrade')}"
    elif not insert_after:
        # Append to end of file
        skill_path.write_text(content + "\n\n" + injection, encoding="utf-8")
        return f"  ✅ Applied: {skill_name} — {proposal.get('description', 'upgrade')}"
    else:
        return f"  ⚠️  SKIP — insert_after anchor not found in {skill_name}"

def update_changelog(applied_count, proposals):
    """Append upgrade entry to CHANGELOG.md."""
    date = datetime.now().strftime("%Y-%m-%d")
    entries = "\n".join(f"- {p['skill']}: {p.get('description', 'upgrade')}"
                        for p in proposals if p.get("approved"))

    changelog_entry = f"""
## [Self-Improvement Cycle] — {date}

### Applied Upgrades ({applied_count})
{entries}

### Source
Generated by self_eval.py, reviewed and approved by Yash Kanadhia.
"""
    if CHANGELOG_PATH.exists():
        content = CHANGELOG_PATH.read_text(encoding="utf-8")
        CHANGELOG_PATH.write_text(content + changelog_entry, encoding="utf-8")

def main():
    parser = argparse.ArgumentParser(description="Zeref Skill Updater")
    parser.add_argument("--report", required=True, help="Path to upgrade report JSON")
    parser.add_argument("--dry-run", action="store_true", help="Preview without applying")
    args = parser.parse_args()

    report = load_report(args.report)
    proposals = report.get("proposals", [])

    if not proposals:
        print("No proposals in report.")
        return

    # SAFETY GATE: Only apply approved proposals
    approved = [p for p in proposals if p.get("approved") is True]
    rejected = [p for p in proposals if p.get("approved") is not True]

    print(f"\n🔒 SAFETY GATE: {len(approved)} approved / {len(rejected)} not approved")
    print(f"   Only approved proposals will be applied.\n")

    if args.dry_run:
        print("DRY RUN — no files will be modified.\n")
        for p in approved:
            print(f"  WOULD APPLY: {p.get('skill')} — {p.get('description', '')}")
        return

    results = [apply_upgrade(p) for p in approved]
    for r in results:
        print(r)

    applied_count = sum(1 for r in results if "✅" in r)
    update_changelog(applied_count, approved)

    print(f"\n✅ Applied: {applied_count} upgrades")
    print(f"📝 CHANGELOG.md updated")
    print("Run python3 scripts/zeref-validate.py to verify fleet.\n")

if __name__ == "__main__":
    main()
