"""Generated Markdown views over SQLite v2 canonical state (vNext §6.4).

Every generated file starts with the banner below. Views are strictly
derived: regenerating overwrites any hand edits, which is the point.
"""

from __future__ import annotations

import sqlite3
from datetime import datetime, timezone
from pathlib import Path

BANNER = (
    "<!-- GENERATED BY ZEREF. SOURCE: memory/state/zeref2.sqlite. "
    "DO NOT EDIT DIRECTLY. -->\n"
)

VIEWS_DIR = Path("memory") / "views"

_VIEW_NAMES = (
    "hot", "decisions", "risks", "contradictions",
    "project-context", "capabilities", "active-team", "session-summary",
)


def _rows(conn: sqlite3.Connection, sql: str, params: tuple = ()) -> list[tuple]:
    try:
        return list(conn.execute(sql, params))
    except sqlite3.OperationalError:
        return []


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_none_\n"
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join(["---"] * len(headers)) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out) + "\n"


def _stamp() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def render_all(root: Path | str, conn: sqlite3.Connection) -> list[Path]:
    root = Path(root)
    out_dir = root / VIEWS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for name in _VIEW_NAMES:
        path = out_dir / f"{name}.md"
        path.write_text(_render_view(name, conn), encoding="utf-8")
        written.append(path)
    return written


def _render_view(name: str, conn: sqlite3.Connection) -> str:
    body_fn = {
        "hot": _view_hot,
        "decisions": _view_decisions,
        "risks": _view_risks,
        "contradictions": _view_contradictions,
        "project-context": _view_project_context,
        "capabilities": _view_capabilities,
        "active-team": _view_active_team,
        "session-summary": _view_session_summary,
    }[name]
    return BANNER + f"\n# {name}\n\n_generated {_stamp()}_\n\n" + body_fn(conn)


# --- individual views ------------------------------------------------------

def _view_hot(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT id, kind, title, status, confidence FROM memory_records "
        "WHERE archived=0 ORDER BY updated_at DESC LIMIT 20",
    )
    return _table(["id", "kind", "title", "status", "confidence"], [list(r) for r in rows])


def _view_decisions(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT id, title, summary, evidence_grade, updated_at "
        "FROM memory_records WHERE kind='decision' AND archived=0 "
        "ORDER BY updated_at DESC",
    )
    return _table(["id", "title", "summary", "grade", "updated_at"], [list(r) for r in rows])


def _view_risks(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT id, title, summary, confidence, updated_at "
        "FROM memory_records WHERE kind='risk' AND archived=0 "
        "ORDER BY updated_at DESC",
    )
    return _table(["id", "title", "summary", "confidence", "updated_at"], [list(r) for r in rows])


def _view_contradictions(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT id, side_a, side_b, state, detected_at FROM contradictions "
        "WHERE state != 'resolved' ORDER BY detected_at DESC",
    )
    return _table(["id", "side_a", "side_b", "state", "detected_at"], [list(r) for r in rows])


def _view_project_context(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT kind, COUNT(*) FROM memory_records WHERE archived=0 GROUP BY kind",
    )
    return _table(["kind", "count"], [list(r) for r in rows])


def _view_capabilities(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT id, name, type, lifecycle, current_digest FROM capabilities "
        "ORDER BY lifecycle, name",
    )
    return _table(["id", "name", "type", "lifecycle", "digest"], [list(r) for r in rows])


def _view_active_team(conn: sqlite3.Connection) -> str:
    rows = _rows(
        conn,
        "SELECT r.id, r.state, r.policy, r.created_at "
        "FROM team_runs r WHERE r.state IN ('COMPILED','AUTHORIZED','RUNNING','VERIFYING','PAUSED_PERMISSION','PAUSED_BUDGET','RETRYING') "
        "ORDER BY r.created_at DESC LIMIT 5",
    )
    return _table(["run_id", "state", "policy", "created_at"], [list(r) for r in rows])


def _view_session_summary(conn: sqlite3.Connection) -> str:
    counts = _rows(conn, "SELECT event_type, COUNT(*) FROM memory_events GROUP BY event_type ORDER BY 2 DESC LIMIT 20")
    return _table(["event_type", "count"], [list(r) for r in counts])
